version: "3.8"

services:
  metrics-exporter:
    build: .
    volumes:
      - .:/app
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped
